spring:
  application:
    name: redis-demo
  datasource:
    url: jdbc:mysql://119.23.237.187:3306/db_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 119.23.237.187 # Redis服务器地址
    database: 4 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms
